---
detectors:
  Attribute:
    enabled: false
    exclude: []
  BooleanParameter:
    enabled: true
    exclude: []
  ClassVariable:
    enabled: true
    exclude: []
  ControlParameter:
    enabled: true
    exclude:
    - Mutation::Expression#match_length
  DataClump:
    enabled: true
    exclude: []
    max_copies: 2
    min_clump_size: 2
  DuplicateMethodCall:
    enabled: false
    exclude: []
    max_calls: 1
    allow_calls: []
  FeatureEnvy:
    enabled: false
  # Buggy smell detector
  IrresponsibleModule:
    enabled: false
    exclude: []
  LongParameterList:
    enabled: true
    exclude:
    - Mutation::Matcher::Method::Instance#self.build
    - Mutation::Meta::Example::DSL # 3 vars
    max_params: 2
  LongYieldList:
    enabled: true
    exclude: []
    max_params: 2
  NestedIterators:
    enabled: true
    exclude:
    - Mutation#self.singleton_subclass_instance
    - Mutation::CLI#parse
    - Mutation::Mutator::Node::Arguments#emit_argument_mutations
    - Mutation::Mutator::Node::Resbody#mutate_captures
    - Mutation::Mutator::Util::Array::Element#dispatch
    - Mutation::Parallel::Master#run
    - Mutation::RequireHighjack#self.call
    - Mutation::Selector::Expression#call
    - Parser::Lexer#self.new
    max_allowed_nesting: 1
    ignore_iterators: []
  NilCheck:
    enabled: false
  RepeatedConditional:
    enabled: true
    exclude:
    - Mutation::Mutator
    - Mutation::Meta::Example::DSL
    max_ifs: 1
  TooManyInstanceVariables:
    enabled: true
    exclude:
    - Mutation::Mutator # 4 vars
    - Mutation::Parallel::Master # 4 vars
    - Mutation::Meta::Example::DSL # 4 vars
    max_instance_variables: 3
  TooManyMethods:
    enabled: true
    exclude:
    - Mutation::CLI
    - Mutation::Mutator::Node
    - Mutation::Parallel::Master
    max_methods: 10
  TooManyStatements:
    enabled: true
    exclude:
    - Mutation::CLI#add_debug_options
    - Mutation::CLI#add_environment_options
    - Mutation::Reporter::CLI::Printer::Config#run
    - Mutation::Reporter::CLI::Printer::EnvProgress#run
    - Mutation::Runner#run_driver
    - Mutation::Zombifier::File#self.find
    max_statements: 7
  UncommunicativeMethodName:
    enabled: true
    exclude:
    - Mutation::AST::Sexp#s
    - Mutation::Mutation#sha1
    reject:
    - '/^[a-z]$/'
    - '/[0-9]$/'
    - '/[A-Z]/'
    accept: []
  UncommunicativeModuleName:
    enabled: true
    exclude: []
    reject:
    - '/^.$/'
    - '/[0-9]$/'
    accept: []
  UncommunicativeParameterName:
    enabled: true
    exclude: []
    reject:
    - '/^.$/'
    - '/[0-9]$/'
    - '/[A-Z]/'
    accept: []
  UncommunicativeVariableName:
    enabled: true
    exclude: []
    reject:
    - '/^.$/'
    - '/[0-9]$/'
    - '/[A-Z]/'
    accept: ['force_utf32']
  UnusedParameters:
    enabled: true
    exclude: []
  UtilityFunction:
    enabled: true
    exclude:
    - Mutation::AST::Sexp#s
    - Mutation::CLI#reporter
    - Mutation::Integration::Null#call
    - Mutation::Integration::Rspec#parse_example
    - Mutation::Integration::Rspec#parse_expression # intentional, private
    - Mutation::Meta::Example::Verification#format_mutations # intentional, private
    - Mutation::Reporter::CLI::Format::Progressive#new_buffer
    - Mutation::Reporter::CLI::Printer::StatusProgressive#object # False positive calls super
    - Mutation::Repository::Diff#tracks? # intentional, private
    - Mutation::Repository::Diff#within_working_directory? # intentional, private
